Get-AppxPackage *3dbuilder* | Remove-AppxPackage
Get-AppxPackage *windowscommunicationsapps* | Remove-AppxPackage
Get-AppxPackage *windowscamera* | Remove-AppxPackage
Get-AppxPackage *windowscamera* | Remove-AppxPackage
Get-AppxPackage *officehub* | Remove-AppxPackage
Get-AppxPackage *skypeapp* | Remove-AppxPackage
Get-AppxPackage *windowsmaps* | Remove-AppxPackage
Get-AppxPackage *bingfinance* | Remove-AppxPackage
Get-AppxPackage *zunevideo* | Remove-AppxPackage
Get-AppxPackage *bingnews* | Remove-AppxPackage
Get-AppxPackage *onenote* | Remove-AppxPackage
Get-AppxPackage *people* | Remove-AppxPackage
Get-AppxPackage *windowsphone* | Remove-AppxPackage
Get-AppxPackage *photos* | Remove-AppxPackage
Get-AppxPackage *bingsports* | Remove-AppxPackage
Get-AppxPackage *soundrecorder* | Remove-AppxPackage
Get-AppxPackage *bingweather* | Remove-AppxPackage
Get-AppxPackage *paint* | Remove-AppxPackage
Get-AppxPackage *alarm* | Remove-AppxPackage
Get-AppxPackage *feedback* | Remove-AppxPackage
Get-AppxPackage *solitaire* | Remove-AppxPackage
Get-AppxPackage *3dviewer* | Remove-AppxPackage
Get-AppxPackage *stickynotes* | Remove-AppxPackage
Get-AppxPackage *people* | Remove-AppxPackage
Get-AppxPackage Microsoft.GetHelp | Remove-AppxPackage
Get-AppxPackage Microsoft.Print3D | Remove-AppxPackage
Get-AppxPackage Microsoft.Wallet | Remove-AppxPackage
Get-AppxPackage Microsoft.Windows.PeopleExperienceHost | Remove-AppxPackage
Get-AppxPackage Microsoft.Messaging | Remove-AppxPackage
Get-AppxPackage Microsoft.Advertising.Xaml | Remove-AppxPackage
Get-AppxPackage Microsoft.Windows.CloudExperienceHost | Remove-AppxPackage       
Get-AppxPackage Microsoft.AAD.BrokerPlugin | Remove-AppxPackage                 
Get-AppxPackage windows.immersivecontrolpanel | Remove-AppxPackage              
Get-AppxPackage Microsoft.Windows.Cortana | Remove-AppxPackage                  
Get-AppxPackage Microsoft.MicrosoftEdge | Remove-AppxPackage                     
Get-AppxPackage Microsoft.Windows.ContentDeliveryManager | Remove-AppxPackage             
Get-AppxPackage Windows.PrintDialog | Remove-AppxPackage                        
Get-AppxPackage Microsoft.XboxGameCallableUI | Remove-AppxPackage               
Get-AppxPackage Microsoft.Windows.PeopleExperienceHost | Remove-AppxPackage     
Get-AppxPackage Microsoft.Windows.ParentalControls | Remove-AppxPackage         
Get-AppxPackage Microsoft.Windows.HolographicFirstRun | Remove-AppxPackage      
Get-AppxPackage Microsoft.Windows.CapturePicker | Remove-AppxPackage            
Get-AppxPackage Microsoft.BioEnrollment | Remove-AppxPackage                    
Get-AppxPackage Microsoft.PPIProjection | Remove-AppxPackage                    
Get-AppxPackage Microsoft.Win32WebViewHost | Remove-AppxPackage                 
Get-AppxPackage Microsoft.Windows.Apprep.ChxApp | Remove-AppxPackage            
Get-AppxPackage Microsoft.Windows.AssignedAccessLockApp | Remove-AppxPackage    
Get-AppxPackage Microsoft.XboxSpeechToTextOverlay | Remove-AppxPackage          
Get-AppxPackage Microsoft.Windows.ShellExperienceHost | Remove-AppxPackage      
Get-AppxPackage Windows.CBSPreview | Remove-AppxPackage                         
Get-AppxPackage Microsoft.Xbox.TCUI | Remove-AppxPackage                        
Get-AppxPackage Microsoft.Wallet | Remove-AppxPackage                           
Get-AppxPackage Microsoft.EdgeDevtoolsPlugin | Remove-AppxPackage               
Get-AppxPackage Microsoft.Messaging | Remove-AppxPackage                        
Get-AppxPackage Microsoft.DesktopAppInstaller | Remove-AppxPackage              
Get-AppxPackage Microsoft.SDKSamples.Logging.CS | Remove-AppxPackage            
Get-AppxPackage Microsoft.Advertising.Xaml | Remove-AppxPackage                 
Get-AppxPackage Microsoft.Advertising.Xaml | Remove-AppxPackage                                    
Get-AppxPackage Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage          
Get-AppxPackage Microsoft.Microsoft3DViewer | Remove-AppxPackage                
Get-AppxPackage Microsoft.GetHelp | Remove-AppxPackage                          
Get-AppxPackage Microsoft.XboxApp | Remove-AppxPackage                          
Get-AppxPackage Microsoft.BingWeather | Remove-AppxPackage                      
Get-AppxPackage Microsoft.WindowsAlarms | Remove-AppxPackage                    
Get-AppxPackage Microsoft.ZuneVideo | Remove-AppxPackage                        
Get-AppxPackage Microsoft.Windows.Photos | Remove-AppxPackage                   
Get-AppxPackage Microsoft.Print3D | Remove-AppxPackage                                    
Get-AppxPackage Microsoft.WindowsMaps | Remove-AppxPackage                      
Get-AppxPackage Microsoft.XboxIdentityProvider | Remove-AppxPackage             
Get-AppxPackage Microsoft.WindowsSoundRecorder | Remove-AppxPackage             
Get-AppxPackage Microsoft.WebMediaExtensions | Remove-AppxPackage               
Get-AppxPackage Microsoft.WindowsCamera | Remove-AppxPackage                    
Get-AppxPackage Microsoft.People | Remove-AppxPackage                           
Get-AppxPackage Microsoft.WindowsFeedbackHub | Remove-AppxPackage               
Get-AppxPackage Microsoft.MicrosoftOfficeHub | Remove-AppxPackage               
Get-AppxPackage Microsoft.WindowsCalculator | Remove-AppxPackage                
Get-AppxPackage Microsoft.MSPaint | Remove-AppxPackage                          
Get-AppxPackage Microsoft.XboxGamingOverlay | Remove-AppxPackage                
Get-AppxPackage Microsoft.SkypeApp | Remove-AppxPackage                         
Get-AppxPackage Microsoft.StorePurchaseApp | Remove-AppxPackage                 
Get-AppxPackage Microsoft.WindowsStore | Remove-AppxPackage                     
Get-AppxPackage Microsoft.ZuneMusic | Remove-AppxPackage                        
Get-AppxPackage Microsoft.OneConnect | Remove-AppxPackage                       
Get-AppxPackage Microsoft.Getstarted | Remove-AppxPackage                       
Get-AppxPackage Microsoft.XboxGameOverlay | Remove-AppxPackage                  
Get-AppxPackage Microsoft.Services.Store.Engagement | Remove-AppxPackage        
Get-AppxPackage Microsoft.Services.Store.Engagement | Remove-AppxPackage        
Get-AppxPackage Microsoft.MicrosoftStickyNotes | Remove-AppxPackage             
Get-AppxPackage Microsoft.Office.OneNote | Remove-AppxPackage                   
Get-AppxPackage microsoft.windowscommunicationsapps | Remove-AppxPackage  

(Get-WmiObject -Class Win32_Product | Where-Object{$_.Name -like "*Azure*"}).Uninstall()
(Get-WmiObject -Class Win32_Product | Where-Object{$_.Name -like "*Visual Studio*"}).Uninstall()
(Get-WmiObject -Class Win32_Product | Where-Object{$_.Name -like "*IIS*"}).Uninstall()
